### ISSUE TITLE
Why add the -master to all the library zip files?

### ISSUE THREAD

**Issue by Gittheheckout** [Futski-III/Arduino-Fast-Clock#3]
Why add the -master to all the library zip files? Arduino won't recognize the -master, and it just makes it very cumbersome to add the libraries. Use _master if you think you need to.

**Comment by per1234** [comment]
>Why add the -master to all the library zip files?

The `-master` is automatically added by GitHub. There's no way to avoid it. `master` is the branch name.

>Arduino won't recognize the -master

Update your Arduino IDE. You must be using a very outdated IDE version. `-` in library folder names has been allowed for years.

**Comment by Gittheheckout** [comment]
Yes, I was using 1.05 on that machine. I loaded 1.8.6 and it is a little smoother.  Thanks.
